/**
 * Product Catalog - Realistic grocery promotions
 * ~25 products per category = ~200 total products
 */

const catalog = {
  Produce: [
    { name: "Broccoli Crowns", unit: "lb", basePrice: 2.49 },
    { name: "Corn on the Cob", unit: "4 ct", basePrice: 3.99 },
    { name: "Gala Apples", unit: "3 lb bag", basePrice: 4.99 },
    { name: "Bananas", unit: "lb", basePrice: 0.59 },
    { name: "Russet Potatoes", unit: "5 lb bag", basePrice: 4.49 },
    { name: "Roma Tomatoes", unit: "lb", basePrice: 1.99 },
    { name: "Baby Carrots", unit: "1 lb bag", basePrice: 2.49 },
    { name: "Iceberg Lettuce", unit: "head", basePrice: 1.99 },
    { name: "Yellow Onions", unit: "3 lb bag", basePrice: 3.49 },
    { name: "Strawberries", unit: "1 lb", basePrice: 4.99 },
    { name: "Blueberries", unit: "6 oz", basePrice: 3.99 },
    { name: "Red Grapes", unit: "lb", basePrice: 2.99 },
    { name: "Avocados", unit: "each", basePrice: 1.49 },
    { name: "Honeycrisp Apples", unit: "lb", basePrice: 3.49 },
    { name: "Organic Baby Spinach", unit: "5 oz", basePrice: 4.99 },
    { name: "Celery Hearts", unit: "16 oz", basePrice: 2.99 },
    { name: "Green Bell Peppers", unit: "each", basePrice: 0.99 },
    { name: "Cucumbers", unit: "each", basePrice: 0.79 },
    { name: "Sweet Potatoes", unit: "lb", basePrice: 1.49 },
    { name: "Lemons", unit: "2 lb bag", basePrice: 3.99 },
    { name: "Limes", unit: "1 lb bag", basePrice: 2.99 },
    { name: "Cantaloupe", unit: "each", basePrice: 3.49 },
    { name: "Watermelon", unit: "each", basePrice: 5.99 },
    { name: "Asparagus", unit: "lb", basePrice: 3.99 },
    { name: "Mushrooms", unit: "8 oz", basePrice: 2.49 }
  ],

  Meat: [
    { name: "Angus Ground Beef 80/20", unit: "lb", basePrice: 5.99 },
    { name: "Boneless Skinless Chicken Breast", unit: "lb", basePrice: 4.49 },
    { name: "Pork Tenderloin", unit: "lb", basePrice: 4.99 },
    { name: "Baby Back Ribs", unit: "rack", basePrice: 12.99 },
    { name: "Atlantic Salmon Fillet", unit: "lb", basePrice: 9.99 },
    { name: "Italian Sausage Links", unit: "19 oz", basePrice: 5.49 },
    { name: "NY Strip Steak", unit: "lb", basePrice: 12.99 },
    { name: "Ground Turkey", unit: "lb", basePrice: 5.49 },
    { name: "Chicken Drumsticks", unit: "lb", basePrice: 1.99 },
    { name: "Bone-In Pork Chops", unit: "lb", basePrice: 3.99 },
    { name: "Tilapia Fillets", unit: "lb", basePrice: 7.99 },
    { name: "Shrimp 21-25 ct", unit: "lb", basePrice: 8.99 },
    { name: "Ribeye Steak", unit: "lb", basePrice: 14.99 },
    { name: "Oscar Mayer Bacon", unit: "16 oz", basePrice: 7.49 },
    { name: "Hillshire Farm Smoked Sausage", unit: "14 oz", basePrice: 4.99 },
    { name: "Chicken Thighs Bone-In", unit: "lb", basePrice: 2.49 },
    { name: "Whole Rotisserie Chicken", unit: "each", basePrice: 7.99 },
    { name: "Deli Sliced Turkey Breast", unit: "lb", basePrice: 8.99 },
    { name: "Deli Sliced Ham", unit: "lb", basePrice: 6.99 },
    { name: "Beef Stew Meat", unit: "lb", basePrice: 6.99 },
    { name: "Ground Pork", unit: "lb", basePrice: 4.49 },
    { name: "Chicken Wings", unit: "lb", basePrice: 3.99 },
    { name: "Cod Fillets", unit: "lb", basePrice: 8.99 },
    { name: "Bratwurst", unit: "19 oz", basePrice: 5.99 },
    { name: "Hot Dogs", unit: "16 oz", basePrice: 4.49 }
  ],

  Dairy: [
    { name: "Horizon Organic Milk", unit: "gal", basePrice: 6.99 },
    { name: "Philadelphia Cream Cheese", unit: "8 oz", basePrice: 4.29 },
    { name: "Land O'Lakes Butter", unit: "1 lb", basePrice: 5.49 },
    { name: "Chobani Greek Yogurt", unit: "5.3 oz", basePrice: 1.49 },
    { name: "Kraft Singles", unit: "16 ct", basePrice: 4.99 },
    { name: "Sargento Shredded Cheese", unit: "8 oz", basePrice: 3.99 },
    { name: "Local: Farm Fresh Eggs", unit: "dozen", basePrice: 4.99 },
    { name: "Organic Valley Milk", unit: "half gal", basePrice: 4.99 },
    { name: "Yoplait Yogurt", unit: "6 oz", basePrice: 0.89 },
    { name: "Tillamook Cheddar Block", unit: "8 oz", basePrice: 4.99 },
    { name: "Daisy Sour Cream", unit: "16 oz", basePrice: 2.99 },
    { name: "Silk Almond Milk", unit: "64 oz", basePrice: 4.49 },
    { name: "Oikos Triple Zero Yogurt", unit: "5.3 oz", basePrice: 1.69 },
    { name: "Laughing Cow Cheese Wedges", unit: "6 oz", basePrice: 4.49 },
    { name: "Cabot Sharp Cheddar", unit: "8 oz", basePrice: 4.49 },
    { name: "Dannon Light & Fit", unit: "5.3 oz", basePrice: 1.29 },
    { name: "Kerrygold Irish Butter", unit: "8 oz", basePrice: 5.99 },
    { name: "Babybel Mini Cheese", unit: "6 ct", basePrice: 5.49 },
    { name: "Reddi-wip Whipped Cream", unit: "6.5 oz", basePrice: 4.29 },
    { name: "I Can't Believe It's Not Butter", unit: "15 oz", basePrice: 4.99 },
    { name: "Fage Total Greek Yogurt", unit: "7 oz", basePrice: 2.29 },
    { name: "Borden American Singles", unit: "16 ct", basePrice: 3.99 },
    { name: "Coffee Mate Creamer", unit: "32 oz", basePrice: 4.99 },
    { name: "Breakstone's Cottage Cheese", unit: "16 oz", basePrice: 3.99 },
    { name: "Local: Artisan Goat Cheese", unit: "4 oz", basePrice: 6.99 }
  ],

  Bakery: [
    { name: "Sara Lee White Bread", unit: "20 oz", basePrice: 3.99 },
    { name: "Thomas' English Muffins", unit: "6 ct", basePrice: 4.49 },
    { name: "Local: Fresh Baked Sourdough", unit: "loaf", basePrice: 5.99 },
    { name: "Entenmann's Donuts", unit: "8 ct", basePrice: 5.49 },
    { name: "Pepperidge Farm Rolls", unit: "8 ct", basePrice: 4.29 },
    { name: "Wonder Bread Classic", unit: "20 oz", basePrice: 3.49 },
    { name: "Arnold Whole Wheat", unit: "24 oz", basePrice: 4.99 },
    { name: "Hostess Twinkies", unit: "10 ct", basePrice: 4.99 },
    { name: "Little Debbie Oatmeal Creme Pies", unit: "12 ct", basePrice: 3.99 },
    { name: "Dave's Killer Bread", unit: "27 oz", basePrice: 6.49 },
    { name: "Local: Cinnamon Rolls", unit: "6 ct", basePrice: 7.99 },
    { name: "King's Hawaiian Rolls", unit: "12 ct", basePrice: 4.99 },
    { name: "Brownberry Oatnut Bread", unit: "24 oz", basePrice: 5.49 },
    { name: "Mission Flour Tortillas", unit: "10 ct", basePrice: 3.49 },
    { name: "Old El Paso Taco Shells", unit: "12 ct", basePrice: 2.99 },
    { name: "Bagels Everything", unit: "6 ct", basePrice: 3.99 },
    { name: "Croissants", unit: "4 ct", basePrice: 4.99 },
    { name: "French Baguette", unit: "each", basePrice: 2.99 },
    { name: "Ciabatta Bread", unit: "loaf", basePrice: 4.49 },
    { name: "Rye Bread", unit: "16 oz", basePrice: 4.29 },
    { name: "Hot Dog Buns", unit: "8 ct", basePrice: 2.99 },
    { name: "Hamburger Buns", unit: "8 ct", basePrice: 2.99 },
    { name: "Local: Apple Pie", unit: "each", basePrice: 9.99 },
    { name: "Pillsbury Crescent Rolls", unit: "8 ct", basePrice: 3.49 },
    { name: "Local: Blueberry Muffins", unit: "4 ct", basePrice: 5.99 }
  ],

  Frozen: [
    { name: "DiGiorno Rising Crust Pizza", unit: "28 oz", basePrice: 8.99 },
    { name: "Ben & Jerry's Ice Cream", unit: "pint", basePrice: 5.99 },
    { name: "Birds Eye Steamfresh Vegetables", unit: "10 oz", basePrice: 2.99 },
    { name: "Eggo Waffles", unit: "10 ct", basePrice: 4.49 },
    { name: "Hot Pockets", unit: "2 ct", basePrice: 3.49 },
    { name: "Stouffer's Lasagna", unit: "10 oz", basePrice: 4.99 },
    { name: "Häagen-Dazs Ice Cream", unit: "14 oz", basePrice: 5.99 },
    { name: "Ore-Ida French Fries", unit: "32 oz", basePrice: 4.99 },
    { name: "Totino's Pizza Rolls", unit: "50 ct", basePrice: 6.99 },
    { name: "Marie Callender's Pot Pie", unit: "15 oz", basePrice: 4.49 },
    { name: "Lean Cuisine Cafe Steamers", unit: "10 oz", basePrice: 3.99 },
    { name: "Amy's Organic Burritos", unit: "6 oz", basePrice: 3.49 },
    { name: "Talenti Gelato", unit: "pint", basePrice: 5.99 },
    { name: "Tyson Chicken Nuggets", unit: "32 oz", basePrice: 9.99 },
    { name: "Green Giant Veggie Tots", unit: "14 oz", basePrice: 4.49 },
    { name: "Red Baron Pizza", unit: "21 oz", basePrice: 5.99 },
    { name: "Banquet Fried Chicken", unit: "29 oz", basePrice: 6.99 },
    { name: "Healthy Choice Power Bowls", unit: "9 oz", basePrice: 4.49 },
    { name: "Breyers Ice Cream", unit: "48 oz", basePrice: 5.99 },
    { name: "Bagel Bites", unit: "9 ct", basePrice: 3.99 },
    { name: "Jimmy Dean Breakfast Sandwiches", unit: "4 ct", basePrice: 6.49 },
    { name: "Birdseye Protein Blends", unit: "13 oz", basePrice: 4.99 },
    { name: "TGI Friday's Appetizers", unit: "15 oz", basePrice: 7.99 },
    { name: "Cool Whip", unit: "8 oz", basePrice: 2.49 },
    { name: "Klondike Bars", unit: "6 ct", basePrice: 5.49 }
  ],

  Beverages: [
    { name: "Coca-Cola", unit: "12 pk cans", basePrice: 7.99 },
    { name: "Tropicana Orange Juice", unit: "52 oz", basePrice: 4.99 },
    { name: "Folgers Coffee", unit: "30 oz", basePrice: 9.99 },
    { name: "Poland Spring Water", unit: "24 pk", basePrice: 5.99 },
    { name: "Gatorade", unit: "8 pk", basePrice: 7.49 },
    { name: "Red Bull", unit: "4 pk", basePrice: 9.99 },
    { name: "Pepsi", unit: "12 pk cans", basePrice: 7.99 },
    { name: "Starbucks Ground Coffee", unit: "12 oz", basePrice: 9.99 },
    { name: "Minute Maid Lemonade", unit: "59 oz", basePrice: 2.99 },
    { name: "LaCroix Sparkling Water", unit: "8 pk", basePrice: 4.99 },
    { name: "Monster Energy", unit: "4 pk", basePrice: 8.99 },
    { name: "Simply Orange Juice", unit: "52 oz", basePrice: 4.49 },
    { name: "Lipton Iced Tea", unit: "12 pk", basePrice: 6.99 },
    { name: "Dunkin' K-Cups", unit: "10 ct", basePrice: 8.99 },
    { name: "Dr Pepper", unit: "12 pk cans", basePrice: 7.99 },
    { name: "Keurig Green Mountain Coffee", unit: "12 ct", basePrice: 9.49 },
    { name: "V8 Vegetable Juice", unit: "46 oz", basePrice: 4.49 },
    { name: "Snapple Iced Tea", unit: "6 pk", basePrice: 6.49 },
    { name: "Nestle Pure Life Water", unit: "28 pk", basePrice: 4.99 },
    { name: "Mountain Dew", unit: "12 pk cans", basePrice: 7.99 },
    { name: "Sprite", unit: "12 pk cans", basePrice: 7.99 },
    { name: "Starbucks Frappuccino", unit: "4 pk", basePrice: 7.99 },
    { name: "Ocean Spray Cranberry Juice", unit: "64 oz", basePrice: 3.99 },
    { name: "Capri Sun Juice Pouches", unit: "10 ct", basePrice: 4.49 },
    { name: "Local: Cold Pressed Juice", unit: "15 oz", basePrice: 7.99 }
  ],

  Snacks: [
    { name: "Lay's Potato Chips", unit: "10 oz", basePrice: 4.99 },
    { name: "Oreo Cookies", unit: "14 oz", basePrice: 5.49 },
    { name: "Doritos Nacho Cheese", unit: "9.5 oz", basePrice: 4.99 },
    { name: "Cheez-It Crackers", unit: "12 oz", basePrice: 4.49 },
    { name: "KIND Bars", unit: "6 ct", basePrice: 8.99 },
    { name: "Goldfish Crackers", unit: "6.6 oz", basePrice: 3.49 },
    { name: "Pringles", unit: "5.5 oz", basePrice: 2.49 },
    { name: "Ritz Crackers", unit: "13.7 oz", basePrice: 4.99 },
    { name: "Chips Ahoy Cookies", unit: "13 oz", basePrice: 4.99 },
    { name: "Tostitos Scoops", unit: "10 oz", basePrice: 4.99 },
    { name: "Nature Valley Granola Bars", unit: "6 ct", basePrice: 4.49 },
    { name: "SunChips Harvest Cheddar", unit: "7 oz", basePrice: 4.49 },
    { name: "Triscuit Crackers", unit: "9 oz", basePrice: 4.99 },
    { name: "M&M's", unit: "10 oz", basePrice: 4.99 },
    { name: "Snickers", unit: "6 ct", basePrice: 5.99 },
    { name: "Planters Mixed Nuts", unit: "10 oz", basePrice: 7.99 },
    { name: "Skinny Pop Popcorn", unit: "4.4 oz", basePrice: 4.49 },
    { name: "Wheat Thins", unit: "9 oz", basePrice: 4.49 },
    { name: "Chex Mix", unit: "8.75 oz", basePrice: 3.99 },
    { name: "Nutter Butter", unit: "10.5 oz", basePrice: 4.49 },
    { name: "Pretzel Crisps", unit: "7.2 oz", basePrice: 4.49 },
    { name: "Smartfood Popcorn", unit: "6.25 oz", basePrice: 4.49 },
    { name: "Fig Newtons", unit: "10 oz", basePrice: 4.99 },
    { name: "Clif Bars", unit: "6 ct", basePrice: 8.49 },
    { name: "Cheetos Crunchy", unit: "8.5 oz", basePrice: 4.99 }
  ],

  Pantry: [
    { name: "Heinz Ketchup", unit: "32 oz", basePrice: 4.99 },
    { name: "Campbell's Chicken Noodle Soup", unit: "10.75 oz", basePrice: 1.99 },
    { name: "Kraft Mac & Cheese", unit: "7.25 oz", basePrice: 1.49 },
    { name: "Barilla Pasta", unit: "16 oz", basePrice: 2.29 },
    { name: "Ragu Pasta Sauce", unit: "24 oz", basePrice: 3.49 },
    { name: "Jif Peanut Butter", unit: "16 oz", basePrice: 4.49 },
    { name: "Skippy Peanut Butter", unit: "16 oz", basePrice: 4.29 },
    { name: "French's Yellow Mustard", unit: "14 oz", basePrice: 2.99 },
    { name: "Hellmann's Mayonnaise", unit: "30 oz", basePrice: 5.99 },
    { name: "Cheerios", unit: "18 oz", basePrice: 5.49 },
    { name: "Quaker Oats", unit: "42 oz", basePrice: 5.99 },
    { name: "Rice-A-Roni", unit: "6.8 oz", basePrice: 1.99 },
    { name: "Hunt's Diced Tomatoes", unit: "14.5 oz", basePrice: 1.49 },
    { name: "Bush's Baked Beans", unit: "28 oz", basePrice: 3.49 },
    { name: "Del Monte Green Beans", unit: "14.5 oz", basePrice: 1.49 },
    { name: "Prego Pasta Sauce", unit: "24 oz", basePrice: 3.99 },
    { name: "Honey Nut Cheerios", unit: "19.5 oz", basePrice: 5.99 },
    { name: "Kellogg's Frosted Flakes", unit: "19.2 oz", basePrice: 5.49 },
    { name: "Lucky Charms", unit: "18.6 oz", basePrice: 5.99 },
    { name: "Uncle Ben's Rice", unit: "32 oz", basePrice: 4.99 },
    { name: "Progresso Soup", unit: "19 oz", basePrice: 3.49 },
    { name: "Classico Pasta Sauce", unit: "24 oz", basePrice: 4.49 },
    { name: "Hidden Valley Ranch", unit: "16 oz", basePrice: 4.99 },
    { name: "Smucker's Grape Jelly", unit: "18 oz", basePrice: 3.99 },
    { name: "Peter Pan Peanut Butter", unit: "16 oz", basePrice: 3.99 }
  ]
};

const dealTypes = ["Fixed Price", "Buy X Get Y For Z", "# for Price", "# / Price", "Amount Off"];

// Calculate totals
const getCatalogStats = () => {
  const stats = { total: 0, byCategory: {} };
  Object.entries(catalog).forEach(([cat, products]) => {
    stats.byCategory[cat] = products.length;
    stats.total += products.length;
  });
  return stats;
};

module.exports = { catalog, dealTypes, getCatalogStats };
